---
title: "DATA_607_Disscussion_11"
author: "Md Jalal Uddin"
date: "December 02, 2016"
output: html_document
---

Question:
Your task is to analyze an existing recommender system that you find interesting. 

You should do the following:

1)Perform a Scenario Design analysis as described below. Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.

2) Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.

3) Include specific recommendations about how to improve the site's recommendation capabilities going forward.

Create your report using an R Markdown file, and create a discussion thread with a link to the GitHub repo where your Markdown file notebook resides. You are not expected to need to write code for this discussion assignment.

Solution:

1) Scenario Design:The recommender sysetem I decided to go with building a survey design online for the participant of my hypertension management research.

The target users are all the participants who are suffering with high blood pressure in Queens and Brooklyn. The goal is to control hypertension, provide education on health and wellness and also get research to data for my organization to the Center for Disease Control (CDC). This can be done monitoring patients high blood pressure over the periond of time, their food and medicine intake, visiting to doctor office. I think it they only need to perform the scenario design for the customers.

2) Reverse Engineering: Also, the organization survey online database should be well manage in consider to the goal we have to reach. For example, education counseling and exercise question must be included in the database.

3) Specific Recommendation: My experince working with research organization and from this course, MySQL would be a good database to implement for this research. By using excess and Redcap the primary data can be recive and for more research we can get help MySQL
